spring:
  mail:
    host: smtp.example.com
    port: 587
    username: your_email@example.com
    password: ${EMAIL_PASSWORD} 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
